### ISSUE TITLE
[Genotype Data] Plink ped/map

### ISSUE THREAD

**Issue by daniel-hui** [kmhernan/awesome-bioinformatics-formats#5]
Plink plain-text genotype format. Mostly has been replaced by bed/bim/fam, but is useful if someone wants to actually look at the SNPs in plain-text since Plink bed is in binary, and also wants to retain more information than from a VCF (eg. additional individual information). 

https://www.cog-genomics.org/plink2/formats#ped

**Comment by kmhernan** [comment]
Good call! And fortunately, I am working on updating EDAM tags this second and will include this in the PR.
